### PR TITLE
added comments to existing routes

### PR DESCRIPTION
**Pull request by JaniPaasiluoto**

### CODE REVIEW

**Review by kwlskiy — APPROVED** [review]
Looks good!
As an alternative we can also use JSDoc style, a book example from the docs:
```JS
/**
 * Represents a book.
 * @constructor
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
function Book(title, author) {
}
```
from this we could also generate automatically documentation

**Comment by JaniPaasiluoto** [comment]
Could it be possible to make this "hacktoberfest-accepted"?

**Comment by kwlskiy** [comment]
@JaniPaasiluoto im not sure exactly what you mean by that, havent looked into hacktoberfest.

**Comment by JaniPaasiluoto** [comment]
Ok, here's some info about it if you're interested:
https://youtu.be/FxBv4FMcDgo

**Comment by kwlskiy** [comment]
Okay, will take a look when i find time!

**Pull request merged**
